version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  target-branch: development
  reviewers:
  - laurent-yoti
  - michaelyoti
  - abdalmajeed-yoti
  assignees:
  - laurent-yoti
