version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  target-branch: development
  reviewers:
  - echarrod
  - davidgrayston
  assignees:
  - davidgrayston
