language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
  - "11"
  - "node"

cache: npm

os:
  - linux
  - osx

install:
  - npm install --only=dev
  - cd ./examples/aml-check && npm update && cd ../../
  - cd ./examples/profile && npm update && cd ../../

script:
  - npm run lint
  - npm test
