language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
  - "11"

cache: npm
  
os:
  - windows
  - linux
  - osx

before_script:
  - npm install --only=dev
  - cd ./examples/aml-check && npm update && cd ../../
  - cd ./examples/profile && npm update && cd ../../

script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      npm run lint
    fi
  - npm test
  