language: node_js

cache: npm

git:
  depth: 1

jobs:
  include:
    - stage: Test
      node_js: "10"
      before_install: npm install -g npm@latest
      install: npm ci
      script:
        - npm audit
        - npm test
    - &test-compatibility
      stage: Compatibility
      node_js: "node"
      os: linux
      install:
        - npm install
        - npm --depth=9999 update
      script:
        - npm test
    - <<: *test-compatibility
      node_js: "6"
    - <<: *test-compatibility
      node_js: "8"
    - <<: *test-compatibility
      node_js: "9"
    - <<: *test-compatibility
      node_js: "10"
    - <<: *test-compatibility
      node_js: "11"
    - <<: *test-compatibility
      node_js: "12"
    - &test-compatibility-osx
      <<: *test-compatibility
      os: osx
    - <<: *test-compatibility-osx
      node_js: "8"
    - <<: *test-compatibility-osx
      node_js: "10"
    - stage: Lint Examples
      name: AML Check
      node_js: "10"
      install:
        - cd ./examples/aml-check
        - npm update
      script:
        - npm run lint
    - name: Profile
      node_js: "10"
      install:
        - cd ./examples/profile
        - npm update
      script:
        - npm run lint

