const fs = require('fs');

// The scenario ID and .pem file are generated by https://hub.yoti.com when you create your app
// The client SDK ID is generated by https://hub.yoti.com when you publish your app
module.exports = {
  SCENARIO_ID: process.env.YOTI_SCENARIO_ID, // Your Yoti Scenario ID
  CLIENT_SDK_ID: process.env.YOTI_CLIENT_SDK_ID, // Your Yoti Client SDK ID
  PEM_KEY: fs.readFileSync(process.env.YOTI_KEY_FILE_PATH), // The content of your Yoti .pem key
};
