'use strict';

module.exports = Object.freeze({
  API_BASE_URL: 'https://api.yoti.com',
  ON_PEP_LIST_ATTR: 'on_pep_list',
  ON_FRAUD_LIST_ATTR: 'on_fraud_list',
  ON_WATCH_LIST_ATTR: 'on_watch_list',
  GIVEN_NAMES_ATTR: 'given_names',
  FAMILY_NAME_ATTR: 'family_name',
  SSN_ATTR: 'ssn',
  ADDRESS_ATTR: 'address',
  POSTCODE_ATTR: 'post_code',
  COUNTRY_ATTR: 'country',
  ATTR_FAMILY_NAME: 'family_name',
  ATTR_GIVEN_NAMES: 'given_names',
  ATTR_FULL_NAME: 'full_name',
  ATTR_DATE_OF_BIRTH: 'date_of_birth',
  ATTR_AGE_VERIFIED: 'age_verified',
  ATTR_AGE_UNDER: 'age_under:',
  ATTR_AGE_OVER: 'age_over:',
  ATTR_GENDER: 'gender',
  ATTR_NATIONALITY: 'nationality',
  ATTR_PHONE_NUMBER: 'phone_number',
  ATTR_SELFIE: 'selfie',
  ATTR_EMAIL_ADDRESS: 'email_address',
  ATTR_POSTAL_ADDRESS: 'postal_address',
  ATTR_DOCUMENT_DETAILS: 'document_details',
  ATTR_STRUCTURED_POSTAL_ADDRESS: 'structured_postal_address',
  ATTR_DOCUMENT_IMAGES: 'document_images',
  ATTR_APPLICATION_NAME: 'application_name',
  ATTR_APPLICATION_LOGO: 'application_logo',
  ATTR_APPLICATION_URL: 'application_url',
  ATTR_APPLICATION_RECEIPT_BGCOLOR: 'application_receipt_bgcolor',
});
