export let Anchor: protobuf.Type;
export let Attribute: protobuf.Type;
export let AttributeList: protobuf.Type;
export let MultiValue: protobuf.Type;
export let EncryptedData: protobuf.Type;
export let DataEntry: protobuf.Type;
export let ExtraData: protobuf.Type;
export let ThirdPartyAttribute: protobuf.Type;
export let SignedTimestamp: protobuf.Type;
